### ISSUE TITLE
[Bug]: Enzyme error encountered during testing

### ISSUE THREAD

**Issue by Lonely-shang** [xiejay97/react-devui#44]
```mount``` not currently supported React18
I read that the 'enzyme-adapter-react-16.3' is also used ReactDOM.render
```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. 
Until you switch to the new API, your app will behave as if it's running React 17.
```

**Comment by xiejay97** [comment]
> `mount` not currently supported React18 I read that the 'enzyme-adapter-react-16.3' is also used ReactDOM.render
> 
> ```
> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. 
> Until you switch to the new API, your app will behave as if it's running React 17.
> ```

I think we can use [react-testing-library](https://github.com/testing-library/react-testing-library)  to replace Enzyme.
The alpha version is suppot React18 now.

**Comment by Lonely-shang** [comment]
OK
After the Enzyme replacement is completed, I am providing a test。

**Comment by Lonely-shang** [comment]
> > `mount` 目前不支持 React18 我读到'enzyme-adapter-react-16.3'也被使用了 ReactDOM.render
> > ```
> > Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. 
> > Until you switch to the new API, your app will behave as if it's running React 17.
> > ```
> 
> 我觉得我们可以用[react-testing-library](https://github.com/testing-library/react-testing-library) 来代替 Enzyme。 alpha 版本现在支持 React18。

OK
After the Enzyme replacement is completed, I am providing a test。

**Comment by Lonely-shang** [comment]
> > `mount` not currently supported React18 I read that the 'enzyme-adapter-react-16.3' is also used ReactDOM.render
> > ```
> > Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. 
> > Until you switch to the new API, your app will behave as if it's running React 17.
> > ```
> 
> I think we can use [react-testing-library](https://github.com/testing-library/react-testing-library) to replace Enzyme. The alpha version is suppot React18 now.

OK
After the Enzyme replacement is completed, I am providing a test。

**Comment by xiejay97** [comment]
@Lonely-shang Ok now, https://github.com/xiejay97/react-devui/commit/240de7cf78fd838eae94f93ca456f5c6e3862175
